const ALLERGEN_DATA = {
  soy: [
    // Direct Soy Products
    { word: "soy sauce", sub: "Coconut aminos or tamari (if gluten-free)" },
    { word: "tofu", sub: "Chickpeas, seitan, or extra-firm beans" },
    { word: "miso", sub: "Chickpea miso or sunflower seed paste" },
    { word: "soy milk", sub: "Oat, almond, or rice milk" },
    { word: "soybean oil", sub: "Avocado, olive, or grapeseed oil" },
    { word: "edamame", sub: "Green peas or fava beans" },
    { word: "tempeh", sub: "Hemp seed tempeh" },
    { word: "teriyaki", sub: "Coconut aminos with ginger and garlic" },
    { word: "shoyu", sub: "Coconut aminos" },
    { word: "tamari", sub: "Coconut aminos" },
    { word: "natto", sub: "Cooked black beans" },
    // Hidden Soy & Derivatives
    { word: "hydrolyzed soy protein", sub: "Pea or rice protein" },
    { word: "textured vegetable protein", sub: "Chopped mushrooms or lentils" },
    { word: "tvp", sub: "Mushrooms or lentils" },
    { word: "soy lecithin", sub: "Sunflower lecithin (check with doctor first)" },
    { word: "soy albumin", sub: "Aquafaba or egg whites" },
    { word: "soy fiber", sub: "Psyllium husk or oat fiber" },
    { word: "soy grits", sub: "Corn grits or quinoa" },
    { word: "soy isolate", sub: "Whey or pea protein isolate" },
    { word: "kinako", sub: "Toasted almond flour" },
    { word: "yuba", sub: "Rice paper or cabbage leaves" }
  ],
  dairy: [
    // Direct Dairy
    { word: "milk", sub: "Oat, almond, or soy milk" },
    { word: "butter", sub: "Coconut oil, vegan butter, or avocado" },
    { word: "cheese", sub: "Nutritional yeast, cashew cheese, or vegan slices" },
    { word: "cream", sub: "Coconut cream or cashew cream" },
    { word: "yogurt", sub: "Coconut, oat, or soy yogurt" },
    { word: "ghee", sub: "Coconut oil or vegan buttery spread" },
    { word: "sour cream", sub: "Cashew cream with lemon or vegan sour cream" },
    { word: "buttermilk", sub: "Oat milk with 1 tsp lemon juice" },
    { word: "kefir", sub: "Water kefir or coconut kefir" },
    // Hidden Dairy Ingredients
    { word: "whey", sub: "Pea protein or hemp protein" },
    { word: "casein", sub: "Plant-based protein isolates" },
    { word: "caseinate", sub: "Potato or pea starch" },
    { word: "lactose", sub: "Lactose-free products or plant milks" },
    { word: "lactalbumin", sub: "Egg whites or aquafaba" },
    { word: "lactoglobulin", sub: "Plant proteins" },
    { word: "curds", sub: "Tofu crumbles" },
    { word: "custard", sub: "Silken tofu or coconut-based pudding" },
    { word: "nougat", sub: "Nut butter and honey/syrup blend" },
    { word: "recaldent", sub: "Xylitol (in dental products)" }
  ],
  peanuts: [
    { word: "peanut", sub: "Sunflower butter, wowbutter, or pumpkin seeds" },
    { word: "groundnut", sub: "Sunflower seeds or soy nuts" },
    { word: "goober", sub: "Toasted chickpeas" },
    { word: "arachis oil", sub: "Olive or avocado oil" },
    { word: "mixed nuts", sub: "Peanut-free certified nut mixes" },
    { word: "beer nuts", sub: "Pretzels or roasted corn" },
    { word: "mandelonas", sub: "Peanuts soaked in almond flavor (Avoid!)" },
    { word: "satay sauce", sub: "Sunflower butter satay" },
    { word: "monkey nuts", sub: "Seeds or soy nuts" },
    { word: "valencia peanuts", sub: "Sunflower seeds" }
  ],
  treeNuts: [
    { word: "almond", sub: "Oat flour or sunflower seeds" },
    { word: "cashew", sub: "Sunflower seeds or pumpkin seeds" },
    { word: "walnut", sub: "Pumpkin seeds or sunflower seeds" },
    { word: "pecan", sub: "Sunflower seeds" },
    { word: "hazelnut", sub: "Tiger nuts or sunflower seeds" },
    { word: "pistachio", sub: "Pumpkin seeds" },
    { word: "brazil nut", sub: "Pumpkin seeds" },
    { word: "macadamia", sub: "Sunflower seeds" },
    { word: "pine nut", sub: "Hemp hearts or sunflower seeds" },
    { word: "chestnut", sub: "Sunflower seeds" },
    { word: "marzipan", sub: "Seed-based sugar paste" },
    { word: "gianduja", sub: "Chocolate-sunflower seed spread" },
    { word: "praline", sub: "Caramelized seeds" },
    { word: "pignolia", sub: "Hemp seeds" },
    { word: "lychee nut", sub: "Actual lychee fruit (not a nut)" }
  ],
  gluten: [
    // Primary Grains
    { word: "wheat", sub: "Rice, corn, quinoa, or buckwheat flour" },
    { word: "barley", sub: "Rice, corn, or gluten-free oats" },
    { word: "rye", sub: "Gluten-free oats or flaxseed" },
    { word: "spelt", sub: "Quinoa or millet" },
    { word: "kamut", sub: "Sorghum or brown rice" },
    { word: "farro", sub: "Quinoa or buckwheat groats" },
    { word: "durum", sub: "Corn or rice-based pasta" },
    { word: "semolina", sub: "Cornmeal or rice flour" },
    { word: "bulgur", sub: "Quinoa or chopped cauliflower" },
    { word: "couscous", sub: "Quinoa or riced broccoli" },
    { word: "seitan", sub: "Tofu, tempeh, or jackfruit" },
    // Hidden Sources & Additives
    { word: "malt", sub: "Molasses, honey, or agave" },
    { word: "malt extract", sub: "Maple syrup" },
    { word: "malt vinegar", sub: "Apple cider or balsamic vinegar" },
    { word: "brewer's yeast", sub: "Nutritional yeast (check label)" },
    { word: "wheat starch", sub: "Corn, potato, or tapioca starch" },
    { word: "hydrolyzed wheat protein", sub: "Pea or soy protein" },
    { word: "attā", sub: "Chickpea or rice flour" },
    { word: "maida", sub: "Corn starch or rice flour" },
    { word: "panko", sub: "Gluten-free breadcrumbs" },
    { word: "udon", sub: "Rice noodles or Soba (100% buckwheat)" },
    { word: "matzo", sub: "Gluten-free matzo" },
    { word: "triticale", sub: "Certified GF oat flour" },
    { word: "einkorn", sub: "Amaranth or teff" },
    { word: "emmer", sub: "Sorghum" },
    { word: "graham flour", sub: "GF all-purpose flour blend" }
  ],
  kashrut: [
    { word: "pork", sub: "Beef, turkey, or plant-based sausage" },
    { word: "bacon", sub: "Turkey bacon, beef bacon, or coconut bacon" },
    { word: "shrimp", sub: "Scaling fish or plant-based konjac shrimp" },
    { word: "crab", sub: "Kosher surimi (imitation crab) or hearts of palm" },
    { word: "lobster", sub: "Monkfish or firm scaling fish" },
    { word: "shellfish", sub: "Finned and scaled fish" },
    { word: "gelatin", sub: "Agar agar, pectin, or carrageenan" },
    { word: "lard", sub: "Vegetable shortening or coconut oil" },
    { word: "ham", sub: "Beef or turkey pastrami" },
    { word: "calamari", sub: "King oyster mushrooms" },
    { word: "oyster", sub: "Mushroom-based 'oyster' sauce" },
    { word: "eel", sub: "Mackerel or salmon" },
    { word: "catfish", sub: "Cod, tilapia, or snapper" },
    { word: "scallop", sub: "King oyster mushroom rounds" },
    { word: "mussel", sub: "Shiitake mushrooms" }
  ],
  vegetarian: [
    { word: "beef", sub: "Lentils, mushrooms, seitan, or impossible meat" },
    { word: "chicken", sub: "Tofu, soy curls, or cauliflower" },
    { word: "pork", sub: "Jackfruit, tempeh, or seitan" },
    { word: "steak", sub: "Portobello mushroom caps or seitan" },
    { word: "fish", sub: "Tofu with nori seaweed" },
    { word: "anchovies", sub: "Capers, miso paste, or kalamata olives" },
    { word: "duck", sub: "Roasted jackfruit or seitan" },
    { word: "turkey", sub: "Tofu turkey or seitan roast" },
    { word: "pepperoni", sub: "Spiced sun-dried tomatoes or vegan pepperoni" },
    { word: "tuna", sub: "Mashed chickpeas with seaweed" },
    { word: "lamb", sub: "Lentils or seitan with rosemary" },
    { word: "venison", sub: "Walnut and lentil blend" },
    { word: "suet", sub: "Vegetable shortening" },
    { word: "tallow", sub: "Coconut oil" },
    { word: "rennet", sub: "Vegetable-based microbial rennet" }
  ]
};
