// data.js
const ALLERGEN_DATA = {
    soy: [
        { word: "soy sauce", sub: "Coconut aminos or tamari (if gluten-free)" },
        { word: "tofu", sub: "Chickpeas, seitan, or extra-firm beans" },
        { word: "miso", sub: "Chickpea miso or sunflower seed paste" },
        { word: "soy milk", sub: "Oat, almond, or rice milk" },
        { word: "soybean oil", sub: "Avocado, olive, or grapeseed oil" },
        { word: "lecithin", sub: "Sunflower lecithin" },
        { word: "edamame", sub: "Green peas or fava beans" },
        { word: "tempeh", sub: "Hemp seed tempeh" },
        { word: "teriyaki", sub: "Coconut aminos with ginger and garlic" },
        { word: "shoyu", sub: "Coconut aminos" },
        { word: "tamari", sub: "Coconut aminos" },
        { word: "hydrolyzed soy protein", sub: "Pea or rice protein" },
        { word: "textured vegetable protein", sub: "Chopped mushrooms or lentils" },
        { word: "tvp", sub: "Mushrooms or lentils" },
        { word: "natto", sub: "Cooked black beans" }
    ],
    dairy: [
        { word: "milk", sub: "Oat, almond, or soy milk" },
        { word: "butter", sub: "Coconut oil, vegan butter, or avocado" },
        { word: "cheese", sub: "Nutritional yeast, cashew cheese, or vegan slices" },
        { word: "whey", sub: "Pea protein or hemp protein" },
        { word: "casein", sub: "Plant-based protein isolates" },
        { word: "lactose", sub: "Lactose-free products or plant milks" },
        { word: "cream", sub: "Coconut cream or cashew cream" },
        { word: "yogurt", sub: "Coconut, oat, or soy yogurt" },
        { word: "ghee", sub: "Coconut oil or vegan buttery spread" },
        { word: "buttermilk", sub: "Oat milk with 1 tsp lemon juice" },
        { word: "curds", sub: "Tofu crumbles" },
        { word: "custard", sub: "Silken tofu or coconut-based pudding" },
        { word: "pudding", sub: "Chia seed pudding or avocado chocolate mousse" },
        { word: "sour cream", sub: "Cashew cream with lemon or vegan sour cream" }
    ],
    nuts: [
        { word: "peanut", sub: "Sunflower butter, wowbutter, or soy nut butter" },
        { word: "almond", sub: "Oat flour, sunflower seeds, or tiger nuts" },
        { word: "cashew", sub: "Sunflower seeds or pumpkin seeds" },
        { word: "walnut", sub: "Pumpkin seeds or sunflower seeds" },
        { word: "pecan", sub: "Sunflower seeds or pumpkin seeds" },
        { word: "hazelnut", sub: "Toasted sunflower seeds or tiger nuts" },
        { word: "pistachio", sub: "Pumpkin seeds" },
        { word: "brazil nut", sub: "Pumpkin seeds" },
        { word: "macadamia", sub: "Sunflower seeds" },
        { word: "pine nut", sub: "Sunflower seeds or hemp hearts" },
        { word: "pignolia", sub: "Sunflower seeds" },
        { word: "marzipan", sub: "Nut-free seed paste with sugar" },
        { word: "gianduja", sub: "Chocolate-sunflower seed spread" },
        { word: "chestnut", sub: "Sunflower seeds" }
    ],
    kashrut: [
        { word: "pork", sub: "Beef, turkey, or plant-based sausage" },
        { word: "bacon", sub: "Turkey bacon, beef bacon, or coconut bacon" },
        { word: "shrimp", sub: "Scaling fish or plant-based konjac shrimp" },
        { word: "crab", sub: "Kosher surimi (imitation crab) or hearts of palm" },
        { word: "lobster", sub: "Monkfish or firm scaling fish" },
        { word: "shellfish", sub: "Finned and scaled fish" },
        { word: "gelatin", sub: "Agar agar, pectin, or carrageenan" },
        { word: "lard", sub: "Vegetable shortening or coconut oil" },
        { word: "ham", sub: "Beef or turkey pastrami" },
        { word: "calamari", sub: "King oyster mushrooms" },
        { word: "oyster", sub: "Mushroom-based 'oyster' sauce" },
        { word: "eel", sub: "Mackerel or salmon" },
        { word: "catfish", sub: "Cod, tilapia, or snapper" }
    ],
    vegetarian: [
        { word: "beef", sub: "Lentils, mushrooms, seitan, or impossible meat" },
        { word: "chicken", sub: "Tofu, soy curls, or cauliflower" },
        { word: "pork", sub: "Jackfruit, tempeh, or seitan" },
        { word: "steak", sub: "Portobello mushroom caps or seitan" },
        { word: "fish", sub: "Tofu with nori seaweed for ocean flavor" },
        { word: "anchovies", sub: "Capers, miso paste, or kalamata olives" },
        { word: "duck", sub: "Roasted jackfruit or seitan" },
        { word: "turkey", sub: "Tofu turkey or seitan roast" },
        { word: "pepperoni", sub: "Spiced sun-dried tomatoes or vegan pepperoni" },
        { word: "tuna", sub: "Mashed chickpeas with seaweed" }
    ]
};
